name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [release, test-release]
        default: test-release
        description: Release to PyPI or TestPyPI.

jobs:
  tests:
    # run test.yml first to ensure that the test suite is passing
    uses: ./.github/workflows/test.yml

  build_source_dist:
    name: Build source distribution
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.10"

      - name: Build source distribution
        run: |
          pip install build
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels for Python ${{ matrix.python-version }} on ${{ matrix.os }}
    needs: tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        python-version: ["310", "311", "312"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1
        env:
          CIBW_BUILD: cp${{ matrix.python-version }}-*
          CIBW_ARCHS_MACOS: universal2

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          path: wheelhouse
          # https://github.com/actions/upload-artifact/issues/478#issuecomment-1885470013
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}

  release:
    name: Release wheels and source distribution to PyPI
    needs: [build_wheels, build_source_dist]
    runs-on: ubuntu-latest
    permissions:
      # For pypi trusted publishing
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish to PyPi or TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          # set the repository URL to the test PyPI repository if the task is 'test-release'
          # else empty string defaults to production PyPI
          repository-url: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'test-release' && 'https://test.pypi.org/legacy/' || '' }}
